### ISSUE TITLE
No Decode Delegate

### ISSUE THREAD

**Issue by ryanrussell** [technopagan/adept-jpg-compressor#33]
After installing the dependencies, I am getting the following on any jpg:

identify: no decode delegate for this image format `JPEG' @ error/constitute.c/ReadImage/501.

ubuntu@ubuntu-desktop:~/work/adept-jpg-compressor$ /usr/bin/convert -version
Version: ImageMagick 6.7.7-10 2014-03-06 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP    

ubuntu@ubuntu-desktop:~/work/adept-jpg-compressor$ which jpegrescan 
/bin/jpegrescan
ubuntu@ubuntu-desktop:~/work/adept-jpg-compressor$ which SaliencyDetector 
/bin/SaliencyDetector
ubuntu@ubuntu-desktop:~/work/adept-jpg-compressor$ which jpegoptim 
/usr/bin/jpegoptim
ubuntu@ubuntu-desktop:~/work/adept-jpg-compressor$ uname -a
Linux ubuntu-desktop 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

ubuntu@ubuntu-desktop:~/work/adept-jpg-compressor$ ls -l | grep "test.jpg" 
-rw-rw-r-- 1 ubuntu ubuntu   59564 Dec 13 19:51 test.jpg
ubuntu@ubuntu-desktop:~/work/adept-jpg-compressor$ bash adept.sh test.jpg 
identify: no decode delegate for this image format `JPEG' @ error/constitute.c/ReadImage/501.

Thanks in advance for any help. My apologies if this is something simple that I've overlooked.

**Comment by technopagan** [comment]
Thanks Ryan! This is very helpful for documentation!
